//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string documentId { get; set; }
        public string documnetType { get; set; }
        public string documnetUpload { get; set; }
    }
}
