//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplicant
    {
        public int loanId { get; set; }
        public string loanType { get; set; }
        public string loanAccountRequired { get; set; }
        public string applicantName { get; set; }
        public string applicantAdderss { get; set; }
        public string applicantMobile { get; set; }
        public string applicantAadhar { get; set; }
        public string applicantPan { get; set; }
        public int applicantSalary { get; set; }
        public string loanRepaymentMethod { get; set; }
        public int loanRepaymentMonths { get; set; }
        public System.DateTime timestampOfLoan { get; set; }
        public string documentId { get; set; }
    }
}
